### ISSUE TITLE
Failure to post new asset

### ISSUE THREAD

**Issue by jhulbe** [ArtisanByteCrafter/KaceSMA#21]
https://github.com/ArtisanByteCrafter/KaceSMA/blob/7a01696b3e8e688deed37149b703f1c8869dac3c/private/New-ApiPOSTRequest.ps1#L74

Invoke-restMehtod @IRMSplat is failing with a 500 Internal Server error when using New-SMAAsset

Kace appliance logs say "PUT /api/asset/assets HTTP/1.1" 500 86 1311 1055 0 

Referencing API documentation the method for creating a new asset is a POST to /api/asset/assets. Changed the method of $IRMSplat to POST and it works successfully.

**Comment by ArtisanByteCrafter** [comment]
Thanks! Looks like a regression with a code refactor. I'll get it updated.

**Comment by ArtisanByteCrafter** [comment]
Fixed - please update your module:

```
Update-Module KaceSMA
```

**Comment by jhulbe** [comment]
Thanks!
